name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step to set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        id: setup-r
        with:
           r-version: '4.5.0' # Explicitly set R version

      - name: Print R_HOME after setup # <-- DEBUG STEP 1
        run: | # Use multi-line indicator
          echo "R_HOME is: $R_HOME"

      # Install system dependencies for R packages (BEFORE installing R packages)
      - name: Install R System Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::data.table
            any::coloc

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: | # Use multi-line indicator
          python -m pip install --upgrade pip
          pip install numpy scipy pandas pytest bitarray duckdb pyarrow rpy2

      # Step to install R packages (after system dependencies)
      - name: Install R dependencies
        run: | # Use multi-line indicator
          Rscript -e 'install.packages(c("data.table", "coloc"), repos = "https://cloud.r-project.org/")'

      - name: Download and install plink
        run: | # Use multi-line indicator
          PLINK_URL="https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20231211.zip"
          wget -q $PLINK_URL -O plink_linux_x86_64.zip
          unzip plink_linux_x86_64.zip -d plink
          sudo mv plink/plink /usr/local/bin/
          rm -rf plink_linux_x86_64.zip plink

      - name: Run unit tests
        run: pytest tests/unit_tests_mr_link_2.py # Single line is okay, but | is safer

      - name: Run integration tests
        run: pytest tests/integration_tests_mr_link_2.py # Single line is okay, but | is safer
      - name: Run comparison_tests_with_r_imlementation
        # Removed the env: block as we'll set vars in the script
        run: |
          echo "--- Debug Info ---"
          echo "Attempting to get R_HOME using 'R RHOME' command..."
          # Execute 'R RHOME' and capture the output
          R_HOME_DETECTED=$(R RHOME)

          # Check if we got a path
          if [[ -z "$R_HOME_DETECTED" ]]; then
            echo "ERROR: 'R RHOME' command failed or returned empty output."
            # Optionally, try the hardcoded path seen before as a fallback for debugging
            echo "Attempting fallback hardcoded path..."
            R_HOME_DETECTED="/opt/R/4.5.0"
            if [[ ! -d "$R_HOME_DETECTED" ]]; then
               echo "ERROR: Fallback path $R_HOME_DETECTED does not exist. Exiting."
               exit 1
            fi
          fi

          echo "Using R_HOME path: $R_HOME_DETECTED"

          # Export R_HOME so pytest (and rpy2) can see it
          export R_HOME="$R_HOME_DETECTED"

          # Construct and export LD_LIBRARY_PATH using the detected R_HOME
          # Assuming standard $R_HOME/lib structure
          R_LIB_DIR="$R_HOME/lib"
          export LD_LIBRARY_PATH="$R_LIB_DIR:${LD_LIBRARY_PATH}"

          echo "R_HOME exported as: $R_HOME"
          echo "LD_LIBRARY_PATH exported as: $LD_LIBRARY_PATH"
          echo "Listing contents of R_LIB_DIR ($R_LIB_DIR):"
          ls -l "$R_LIB_DIR" || echo "Failed to list $R_LIB_DIR"
          echo "--- End Debug Info ---"

          # Run pytest - it should inherit the exported variables
          pytest tests/test_for_r_and_python_concordance.py
