name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy pandas pytest bitarray duckdb pyarrow

      # Step to set up R
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      # Step to install R packages (arrow, dplyr, MRAPSS, etc.)
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("data.table", "coloc"), repos = "https://cloud.r-project.org/")'

      - name: Download and install plink
        run: |
          PLINK_URL="https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20231211.zip"
          wget -q $PLINK_URL -O plink_linux_x86_64.zip
          unzip plink_linux_x86_64.zip -d plink
          sudo mv plink/plink /usr/local/bin/
          rm -rf plink_linux_x86_64.zip plink

      - name: Run unit tests
        run: pytest tests/unit_tests_mr_link_2.py

      - name: Run integration tests
        run: pytest tests/integration_tests_mr_link_2.py
